server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username:
    password:
    #tomcat:
      #test-while-idle: true
      #time-between-eviction-runs-millis: 3600000
      #validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    #database: mysql
    show-sql: true

logging:
  file: logs/test.log
  level: info

quartz:
  enabled: true

testJob:
  frequency: 2000

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

